version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      bundler-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/google_scholar_crawler"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
